// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Infrastructure.Persistence;

#nullable disable

namespace OrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Domain.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_path");

                    b.Property<string>("ResourceLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource_location");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<short?>("ResponseStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("PROCESSING")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_requests");

                    b.HasIndex("OrderId");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_idempotency_completed_created_at")
                        .HasFilter("state = 'COMPLETED'");

                    b.HasIndex("Scope", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotency_scope_key");

                    b.ToTable("idempotency_requests", "public", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_completion", "(state = 'PROCESSING' AND completed_at IS NULL AND response_status IS NULL AND response_body IS NULL AND order_id IS NULL AND resource_location IS NULL) OR (state = 'COMPLETED' AND completed_at IS NOT NULL AND response_status IS NOT NULL AND response_body IS NOT NULL)");

                            t.HasCheckConstraint("ck_idempotency_fingerprint_sha256", "octet_length(request_fingerprint) = 32");

                            t.HasCheckConstraint("ck_idempotency_http_status", "response_status IS NULL OR response_status BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_idempotency_key_canonical", "length(btrim(idempotency_key)) > 0 AND idempotency_key = btrim(idempotency_key)");

                            t.HasCheckConstraint("ck_idempotency_path_canonical", "length(btrim(request_path)) > 0 AND request_path = btrim(request_path)");

                            t.HasCheckConstraint("ck_idempotency_scope_canonical", "length(btrim(scope)) > 0 AND scope = btrim(scope)");

                            t.HasCheckConstraint("ck_idempotency_state", "state IN ('PROCESSING', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("OrderService.Domain.Inventory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductId")
                        .HasName("pk_inventories");

                    b.ToTable("inventories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inventories_available_nonnegative", "available_quantity >= 0");

                            t.HasCheckConstraint("ck_inventories_reserved_nonnegative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("OrderService.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("order_number");

                    b.Property<DateTimeOffset>("ReservationExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_expired_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_orders_order_number");

                    b.HasIndex("ReservationExpiredAt", "Id")
                        .HasDatabaseName("ix_orders_pending_expiry")
                        .HasFilter("status = 'PENDING'");

                    b.ToTable("orders", "public", t =>
                        {
                            t.HasCheckConstraint("ck_orders_event_times", "(confirmed_at IS NULL OR confirmed_at >= created_at) AND (cancelled_at IS NULL OR cancelled_at >= created_at)");

                            t.HasCheckConstraint("ck_orders_expiry_after_create", "reservation_expired_at > created_at");

                            t.HasCheckConstraint("ck_orders_number_not_blank", "length(btrim(order_number)) > 0");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED')");

                            t.HasCheckConstraint("ck_orders_terminal_timestamps", "(status = 'PENDING' AND confirmed_at IS NULL AND cancelled_at IS NULL) OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND cancelled_at IS NULL) OR (status = 'CANCELLED' AND confirmed_at IS NULL AND cancelled_at IS NOT NULL) OR (status = 'EXPIRED' AND confirmed_at IS NULL AND cancelled_at IS NULL)");

                            t.HasCheckConstraint("ck_orders_total_nonnegative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("OrderService.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("pk_order_items");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", "public", t =>
                        {
                            t.HasCheckConstraint("ck_order_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_unit_price_nonnegative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("OrderService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_products_sku");

                    b.ToTable("products", "public", t =>
                        {
                            t.HasCheckConstraint("ck_products_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_price_nonnegative", "price >= 0");

                            t.HasCheckConstraint("ck_products_sku_canonical", "length(btrim(sku)) > 0 AND sku = upper(btrim(sku))");
                        });
                });

            modelBuilder.Entity("OrderService.Domain.IdempotencyRequest", b =>
                {
                    b.HasOne("OrderService.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OrderService.Domain.Inventory", b =>
                {
                    b.HasOne("OrderService.Domain.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("OrderService.Domain.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderService.Domain.OrderItem", b =>
                {
                    b.HasOne("OrderService.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderService.Domain.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderService.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderService.Domain.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
